# -*- coding: utf-8 -*-
"""Heroku Song Downloader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FZJjOLKwXerE9AL4Pd3INYIbL5h7s3e-
"""

import subprocess, os
from pytube import YouTube
import json
import urllib
from flask import Flask, send_file, request
app = Flask(__name__)

@app.route('/download', methods=['GET'])
def return_mp3():
    url = request.args.get('url')
    audio = YouTube(url).streams.filter(only_audio=True)
    aud = list(enumerate(audio))
    out_file = audio[0].download()
    base, ext = os.path.splitext(out_file)
    new_name = "_".join(base.split(" "))
    os.rename(out_file, new_name + ".mp4") 
    base = "_".join(base.split(" "))
    music_file = base + '.mp3'
    command = ['ffmpeg', '-i', new_name + ".mp4", '-vn', '-acodec', 'libmp3lame', music_file]
    result = subprocess.run(command)
    if result.returncode == 0:
      return send_file(music_file, as_attachment=True)
    else:
      return "Some error occurred"